# Azure Web Apps Deploy Action for Sihnew
name: Build and deploy to Azure Web App - Sihnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies & Build HTML
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python build_static.py

      - name: Login to Azure using OpenID Connect
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDCD0CD807E5446393AE0AB3979588AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_12F064D360BA4C4D99A52FA63E2FA340 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34888C27C5E54270A3BE0A52099B3359 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sihnew'
          slot-name: 'Production'
          package: .